### PR TITLE
Add High-Level Editing Handlers

### PR DESCRIPTION
**Pull request by justinnhli**
* detect cursor changes with onDidChangeCursorSelection
* direct all changes through one of onPointInsert, onPointBackspace, onPointDelete, onRangeReplace, and onRangeDelete
* create and save editor state

### CODE REVIEW

**Comment by justinnhli** [comment]
@ccullip take a look at the changes and comment if you see anything suspicious

**Comment by ccullip** [comment]
Is there an easy way for me to test the brick-editor.js? I'm a little confused on how deleting a character if the editor is unparsable would work. Right now it seems like the backspaceHandler would call onPointBackspace which would then call UpdateEditorState which wouldn't do anything. Unless I'm missing something.

**Comment by justinnhli** [comment]
You can checkout my branch and run it?

**Comment by ccullip** [comment]
Did you intend to make backspace and delete not work if unparsable?

**Comment by justinnhli** [comment]
Yes within the region we allow edits. There's probably another function we need to write that checks both parseable and if the cursor is in that region.

**Comment by ccullip** [comment]
Okay, looks fine to me then.

**Pull request merged**
