### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by PlamenIlchevski**
Autocompletion done

### CODE REVIEW

**Comment by justinnhli** [comment]
Please rebase your code on master first.

**Comment by PlamenIlchevski** [comment]
The changed files should be in my last upload. I have made changes to 3 files: brick-editor.js, stylesheet.css and index.html. I accidentally closed the pull request.

**Comment by justinnhli** [comment]
As before, please rebase your code first.

**Comment by PlamenIlchevski** [comment]
Okay, I will make sure I do ASAP.

**Pull request closed without merging**
